# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.5.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-06-15T20:10:37Z"
  labels:
    app: yaiballprincess
  name: yaiballprincess
spec:
  containers:
  - args:
    - postgres
    env:
    - name: POSTGRES_USER
      value: theroot
    - name: POSTGRES_PASSWORD
      value: thepassword
    - name: POSTGRES_DB
      value: yibp_db
    image: docker.io/library/postgres:15.3
    name: yaiballprincess-db
    ports:
    - containerPort: 5432
      hostPort: 5433
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: yibp-db-pvc
  volumes:
  - name: yibp-db-pvc
    persistentVolumeClaim:
      claimName: yibp-db

